org: lucaslimao
app: musii

service: musii-sns-services

provider:
    name: aws
    runtime: nodejs12.x
    memorySize: 512
    timeout: 10
    iamRoleStatements:
        - Effect: "Allow"
          Action:
          - "sns:*"
          Resource: "*"

functions:
    worker:
        handler: src/handlers/handler.worker
        onError: ARN_DLQ_TOPIC